Add friends and films likes
notbadcodecom/java-filmorate pull request #3
Opened 2022-07-06 18:07 UTC by notbadcodecom

Сделано:
- рефакторинг, замена пакета data, который хранил в памяти данные на пакет storage;
- сделана логика пакета storage: сохранять и отдавать данные;
- добавлены сервисы для работы с пользователями и фильмами;
- изменена логика работы контролера: теперь контроллер только передает входные данные в сервисы;
- сделан общий error handler;
- добавлены эндпоинты:
    - для добавления-удаления подписок пользователей;
    - для добавления-удаления оценок фильмов;
    - для получения данных общих друзей;
    - для получения рейтинга фильмов.

2022-07-07 22:40 UTC, ddddemo1984 requested changes

2022-07-07 22:40 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Не вижу удаление лайка и  вывод 10 наиболее популярных фильмов

2022-07-07 22:40 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import java.util.Optional;
Все неиспользуемые импорты нужно удалить

2022-07-07 22:40 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmScoreService.java
> +public class FilmScoreService {
В чём смысл этого класса, почему нельзя было реализовать его функциональность в FilmService ?

2022-07-08 07:51 UTC, notbadcodecom commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmScoreService.java
> +public class FilmScoreService {
Сделал один сервис

2022-07-08 08:31 UTC, notbadcodecom commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Объединил сервисы

2022-07-08 08:33 UTC, notbadcodecom commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Объединил сервисы

2022-07-08 08:35 UTC, notbadcodecom commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage extends InMemoryLikeStorageStorage implements Storage<Film> {
разделил интерфейс на два и объединил оба интерфейса с интерфейсом работы с лайками

2022-07-08 18:32 UTC, merged